### ISSUE TITLE
[BUG] content 包含 / 或 @ 时可能无法发送

### ISSUE THREAD

**Issue by txtxj** [liuly0322/QQAutoGUISender#3]
RT

https://github.com/liuly0322/QQAutoGUISender/blob/52b7d41b4414203f769db1be25124983461c6ffe/message_sender.py#L59

=>

```py
 pyautogui.press(['esc', 'enter'])
```

**Comment by liuly0322** [comment]
cf755a17ce2b9bc94d206caf789d22251fdc86ea

Thanks!
